## CSCI-467 Discussion (Week 1)

### Rules

1. Please read the instructions and problem prompts **carefully**.
2. This lab is to give you some basic APIs of numpy, pandas and scikit-learn. The lab is to be done individually. You may talk to your fellow classmates about general issues ("Remind me again: Which API should I used for doing group by operation to a data set") but about the specifies of how to do these exercises.
3. Along with a similar vein, you can ask the TA for help, but ask questions about **concepts** but not ask the TA to help you debug your code. The TA is here to help, but not to do the work for you.
4. You are welcome to use the class resources and the Internet.
5. Playing with variations. Solve one problems, and then copy the code to a new cell and play around with it. Doing this is the single most important thing when learning programming.
6. This lab will not be graded but the content is highly related to your future programming assignments. So, treat it wisely.
7. All the content having been gone though in the week 1 discussion is just a snapshot of the most basic concepts. **You need to keep study more about Git, GitHub, Pandas, Numpy and Scikit-Learn in order to finish your programming assignments successfully.**
8. Have fun!

### Setup Development Environment

There are many ways to setup the environment. But, I do recommend a simple idea that is using the Anaconda, which is a pre-build python environment with bundles of useful packages.

**To download the Anaconda, go to the following website:
https://www.anaconda.com/distribution/**. Download the correct version based on your operating system and install it step by step.

Then, **configure your PATH environment variable** to make the conda command work. The following command is an easy way to test whether your configuration is correct. If it is, you will see something as like as the sample output.

> **command:**
>
> conda --version
>
> **sample output:**
>
> conda 4.6.12

**Finally, download this jupyter notebook file,** then change the working directory to where its location in terminal, and type the following command to open the jupter notebook and finish the lab.

> **command:** 
> jupyter notebook

### Pandas

#### The read_csv() Method

First, read the documentation about the *read_csv()* method in Pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Then, try to read data from file Salaries.csv to a dataframe, make the column playerID in the csv file as the index column and the first row as the header. Also, skip the second row when reading the file.

In [14]:
import pandas as pd
import numpy as np
table1 = pd.read_csv ('Salaries.csv',header = 0,index_col = 3,skiprows = [1])
print(table1)
DF = pd.DataFrame(data = table1)
DF

           yearID teamID lgID    salary
playerID                               
barkele01    1985    ATL   NL    870000
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25575 rows x 4 columns]


yearID teamID lgID    salary
playerID                               
barkele01    1985    ATL   NL    870000
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25575 rows x 4 columns]

#### Indexing and Selecting Data

Select the id of the players who are registered in ATL and HOU and whose salary is higher than one million.

In [98]:
table2 = pd.read_csv ('Salaries.csv',header = 0,skiprows = [1])
print(table2)


DF_SORT = table2[((table2['teamID']=='ATL')|(table2['teamID']=='HOU')) & (table2['salary']>1000000)]
print(DF_SORT)


DF_SORT_PLAYERID = DF_SORT['playerID']
print(DF_SORT_PLAYERID)

#table2 = pd.read_csv ('Salaries.csv',header = 0,index_col = False,skiprows = [1])
#print(table2)
#DF1 = pd.DataFrame(data = table2)
#DF1

#DF_SORT = DF1[((DF1['teamID']=='ATL')|(DF1['teamID']=='HOU')) & (DF1['salary']>1000000)]
#print(DF_SORT)
#DF_SORT_PLAYERID_DF = pd.DataFrame(data = DF_SORT)
#DF_SORT_PLAYERID_DF

#DF_SORT_PLAYERID = DF_SORT_PLAYERID_DF['playerID']
#print(DF_SORT_PLAYERID)

       yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
...       ...    ...  ...        ...       ...
25570    2015    WAS   NL  treinbl01    512800
25571    2015    WAS   NL  ugglada01    507500
25572    2015    WAS   NL  werthja01  21000000
25573    2015    WAS   NL  zimmejo02  16500000
25574    2015    WAS   NL  zimmery01  14000000

[25575 rows x 5 columns]
       yearID teamID lgID   playerID   salary
10       1985    ATL   NL  hornebo01  1500000
15       1985    ATL   NL  murphda05  1625000
20       1985    ATL   NL  suttebr01  1354167
216      1985    HOU   NL   ryanno01  1350000
559      1986    ATL   NL  hornebo01  1800000
...       ...    ...  ...        ...      ...
25053    2015    HOU   AL  quallch01  3000000
25054    2015    HOU   AL  rasmuco01  8000

#### The describe() Method

Calculate the standard Deviation, first quartile, medium, third quartile, mean, maximum, minimum of the salary in team ATL.

In [105]:
perc =[.20, .40, .60, .80]
table2_ATL = table2[table2['teamID']=='ATL']
print(table2_ATL)
desc = table2_ATL['salary'].describe(percentiles = perc)
desc

       yearID teamID lgID   playerID   salary
0        1985    ATL   NL  barkele01   870000
1        1985    ATL   NL  bedrost01   550000
2        1985    ATL   NL  benedbr01   545000
3        1985    ATL   NL   campri01   633333
4        1985    ATL   NL  ceronri01   625000
...       ...    ...  ...        ...      ...
24806    2015    ATL   NL  simmoan01  3000000
24807    2015    ATL   NL  teherju01  1000000
24808    2015    ATL   NL  terdojo01   507500
24809    2015    ATL   NL   woodal02   520000
24810    2015    ATL   NL  younger03  1000000

[886 rows x 5 columns]


count    8.860000e+02
mean     2.206239e+06
std      3.432673e+06
min      6.000000e+04
20%      2.200000e+05
40%      4.500000e+05
50%      6.000000e+05
60%      8.800000e+05
80%      3.420000e+06
max      1.606180e+07
Name: salary, dtype: float64

#### The iterrows() Method

Create a Python dictionary object whose keys are the headers of the dataframe created in the read_csv() exercise and values are Python list objects that contain data corresponding to the headers. (Here, use the iterrows method to iterate each row of the dataframe and copy it to a dictionary. However, there is a easier way. Learn how the to_dict() method works by yourself later)

In [200]:
#for index,value in table2.iterrows():
   #  print(value['teamID'])
    # dict = {'yearID':value['yearID'],'teamID':value['teamID'],'lgID':value['lgID'],'playerID':value['playerID'],'salary':value['salary']}# print(value['yearID'])
   #  print(dict)   

DICT = table2.to_dict()
print(DICT)



    # print(value['teamID'])
    
    # print(value['lgID'])
        
    # print(value['playerID'])
    
    # print(value['salary'])

        
       
# Creating a data frame along with column name
#df = pd.DataFrame([[2, 2.5, 100, 4.5, 8.8, 95]], columns=[
               #   'int', 'float', 'int', 'float', 'float', 'int'])
  

# # using df.iterrows()
#for i,r in df.iterrows():
   # print(r)

{'yearID': {0: 1985, 1: 1985, 2: 1985, 3: 1985, 4: 1985, 5: 1985, 6: 1985, 7: 1985, 8: 1985, 9: 1985, 10: 1985, 11: 1985, 12: 1985, 13: 1985, 14: 1985, 15: 1985, 16: 1985, 17: 1985, 18: 1985, 19: 1985, 20: 1985, 21: 1985, 22: 1985, 23: 1985, 24: 1985, 25: 1985, 26: 1985, 27: 1985, 28: 1985, 29: 1985, 30: 1985, 31: 1985, 32: 1985, 33: 1985, 34: 1985, 35: 1985, 36: 1985, 37: 1985, 38: 1985, 39: 1985, 40: 1985, 41: 1985, 42: 1985, 43: 1985, 44: 1985, 45: 1985, 46: 1985, 47: 1985, 48: 1985, 49: 1985, 50: 1985, 51: 1985, 52: 1985, 53: 1985, 54: 1985, 55: 1985, 56: 1985, 57: 1985, 58: 1985, 59: 1985, 60: 1985, 61: 1985, 62: 1985, 63: 1985, 64: 1985, 65: 1985, 66: 1985, 67: 1985, 68: 1985, 69: 1985, 70: 1985, 71: 1985, 72: 1985, 73: 1985, 74: 1985, 75: 1985, 76: 1985, 77: 1985, 78: 1985, 79: 1985, 80: 1985, 81: 1985, 82: 1985, 83: 1985, 84: 1985, 85: 1985, 86: 1985, 87: 1985, 88: 1985, 89: 1985, 90: 1985, 91: 1985, 92: 1985, 93: 1985, 94: 1985, 95: 1985, 96: 1985, 97: 1985, 98: 1985, 99: 1985

#### Create Dataframe Using the Constructor

Read the documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame and create a dataframe using pd.DataFrame from the dictionary created in the iterrows() exercise. Change the header to "a", "b", "c", ... at creation time.

In [207]:
table3 = pd.DataFrame(data=DICT)
table3.columns = ['a', 'b', 'c','d','e']
table3

a    b   c          d         e
0      1985  ATL  NL  barkele01    870000
1      1985  ATL  NL  bedrost01    550000
2      1985  ATL  NL  benedbr01    545000
3      1985  ATL  NL   campri01    633333
4      1985  ATL  NL  ceronri01    625000
...     ...  ...  ..        ...       ...
25570  2015  WAS  NL  treinbl01    512800
25571  2015  WAS  NL  ugglada01    507500
25572  2015  WAS  NL  werthja01  21000000
25573  2015  WAS  NL  zimmejo02  16500000
25574  2015  WAS  NL  zimmery01  14000000

[25575 rows x 5 columns]

### Numpy

Quick start: https://www.numpy.org/devdocs/user/quickstart.html

Numpy axes explaination: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

#### The np.array Method

Example 1:

```python
ls = [1, 2, 3]
arr = np.array(ls)
```

Example 2:
```python
>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])
```

Now, create a 2-dimensional Python list object, then convert it to a Numpy array object.

In [220]:
aaa = [[1., 0., 0.],
 [0., 1., 2.]]
bbb = np.array(aaa)
print(bbb)


[[1. 0. 0.]
 [0. 1. 2.]]


0.6666666666666666

#### ndarray Objects' Attributes

Play with the **ndim, shape, size, dtype, itemsize and data** attribute.

Example:

```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.ndim
2
```

#### Dimension of ndarray Ojects

Play with the reshape() and flatten() method.

Example:
```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.flatten()
array([1, 2, 3, 4])
```

#### The Slice Operation of ndarray Objects

Understand how the slice operation works for 1-D array and 2-D array.

Example:

```python
>>> arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
>>> arr[1:]
array([[3, 4, 6],
       [7, 8, 9]])
>>> arr[1:, 0:2]
array([[3, 4],
       [7, 8]])
```

#### The Calculation of ndarray Objects

Play with the **argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), mod()** method.

Example:

```python
>>> np.square(array)
array([[ 1,  4,  9],
       [ 9, 16, 36],
       [49, 64, 81]])

```

In [234]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))

c = np.dot(a, b)[2,3,2,1,2,2]
print(c)
#np.dot(a, b)[2,3,2,1,2,2]

#sum(a[2,3,2,:] * b[1,2,:,2])


499128


#### Other Important Methods Inside Module Numpy

Play with the arange(), ones(), zeros(), eye(), linspace(), concatenate() method.

Example:

```python
>>> np.eye(3)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

### Scikit-Learn

The followings are packages (or methods) in Python (Scikit-Learn and Scipy) that will be frequently used in your programming assignment. So, please read carefully.

- Data Preprocessing (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing)
    - Standardization: StandardScaler
    - Normalization: MinMaxScaler
    - Quantifing Categorical Features: LabelEncoder. OneHotEncoder
    - Construct Train and Test Set: model_selection.train_test_split
- KNN: KNeighborsClassifier
- Linear Regression: LinearRegression
- Logistic Regression: LogisticRegression, LogisticRegressionCV
- Feature Selection / Model Selection
    - L1 Penalized Regression (Lasso Regression) with Cross-Validation: LassoCV
    - L2 Penalized Regression (Ridge Regression) with Cross-Validation: RidgeCV
    - Cross-Validation: StratifiedKFold, RepeatedKFold, LeaveOneOut, KFold, model_selection.cross_validate, model_selection.cross_val_predict, model_selection.cross_val_score
    - Model Metrics (https://scikit-learn.org/stable/modules/classes.html#sklearn-metrics-metrics): accuracy_score, auc, f1_score, hamming_loss, precision_score, recall_score, roc_auc_score
- Decision Tree: DecisionTreeClassifier, DecisionTreeRegressor
- Bootstrap, Ensemble Methods
    - Bootstrap: bootstrapped (https://pypi.org/project/bootstrapped/)
    - Bagging: RandomForestClassifier, RandomForestRegressor
    - Boosting: AdaBoostClassifier, AdaBoostRegressor
- Support Vector Machines (https://scikit-learn.org/stable/modules/svm.html#svm): LinearSVC, LinearSVR
- Multiclass and Multilabel Classification (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.multiclass)
    - One-vs-one Multiclass Strategy: OneVsOneClassifier
    - One-vs-the-rest (OvR) multiclass/multilabel strategy / OneVsRestClassifier
- Unsupervised Learning
    - K-means Clustering: KMeans
    - Hierarchical Clustering: scipy.cluster.hierarchy (not scikit-learn)
- Semisupervised Learning (https://scikit-learn.org/stable/modules/label_propagation.html)

### Git and GitHub

1. In the directory that where this jupyter notebook file locates in, init a Git repository.
2. Checkout a new branch called dev and commit the current notebook within this branch.
3. Merge the dev branch to the master branch (the default branch).
4. Create a temporary repository (just for practicing and you can delete it later) in GitHub. 
5. Push new changes in the master branch to the remote repository created in step 4.
6. Checkout the dev branch again and do some changes to your notebook, and then repeat step 3 and step 5.